version: "2"

services:
  remark:
    # remove the next line in case you want to use this docker-compose separately
    # as otherwise it would complain for absence of Dockerfile
    build: .
    image: umputun/remark42:latest
    container_name: "remark42"
    hostname: "remark42"
    restart: always

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    # uncomment to expose directly (no proxy)
    ports:
     - "80:8080"
    #  - "443:8443"

    environment:
      - REMARK_URL=https://thdngan.github.io/arboretum/
      - SITE=remark
      # - SECRET=
      - DEBUG=true
      - AUTH_ANON=true
    volumes:
      - ./var:/srv/var
      # - /var/run/docker.sock:/var/run/docker.sock
